"""Query-time image resolution for RAG Q&A (Plan B).

Ingest co-locates ``[图片]`` blocks with anchor text in vector chunks (Route A).
This module parses inline refs from LLM-input chunk bodies at finalize (Plan A).
"""

from __future__ import annotations

import base64 as base64
import json as json
import logging as logging
import os as os
import re as re
from functools import lru_cache as lru_cache
from pathlib import Path as Path
from typing import Any as Any, NamedTuple as NamedTuple

from raganything.utils import (
    build_image_ref_block as build_image_ref_block,
    discriminative_terms as discriminative_terms,
    flatten_image_refs_for_skip_multimodal as flatten_image_refs_for_skip_multimodal,
    image_label_for_item as image_label_for_item,
    image_label_text as image_label_text,
    short_label_bag_aligns as short_label_bag_aligns,
    substantive_bigrams as substantive_bigrams,
    text_term_alignment_symmetric as text_term_alignment_symmetric,
)

logger = logging.getLogger(__name__)

from iqr_protocol import (
    FigureTarget as FigureTarget,
    _CAPTION_RE as _CAPTION_RE,
    _CONTEXT_RE as _CONTEXT_RE,
    _FOOTNOTE_RE as _FOOTNOTE_RE,
    _IMAGE_EXTS as _IMAGE_EXTS,
    _IMAGE_EXT_GROUP as _IMAGE_EXT_GROUP,
    _IMAGE_METADATA_MARKERS as _IMAGE_METADATA_MARKERS,
    _IMAGE_PATH_RE as _IMAGE_PATH_RE,
    _LogicLine as _LogicLine,
    _PAGE_RE as _PAGE_RE,
    _append_logic_line as _append_logic_line,
    _image_block_for_path as _image_block_for_path,
    _image_score_for_logic_line as _image_score_for_logic_line,
    _is_image_metadata_line as _is_image_metadata_line,
    _maintenance_topic_from_text as _maintenance_topic_from_text,
    _metadata_from_block as _metadata_from_block,
    extract_image_refs_from_context as extract_image_refs_from_context,
    normalize_context_for_image_parse as normalize_context_for_image_parse,
    normalize_image_path as normalize_image_path,
)
from iqr_media import (
    decode_media_token as decode_media_token,
    encode_media_token as encode_media_token,
    is_safe_media_path as is_safe_media_path,
    resolve_media_path as resolve_media_path,
)
from iqr_config import (
    _MIN_QUERY_CHARS_FOR_IMAGES as _MIN_QUERY_CHARS_FOR_IMAGES,
    _MIN_SUBSTANTIVE_TERM_LEN as _MIN_SUBSTANTIVE_TERM_LEN,
    _env_bool_image as _env_bool_image,
    _env_int_image as _env_int_image,
    _image_min_ref_align as _image_min_ref_align,
    _image_min_rerank_score as _image_min_rerank_score,
    _inline_min_place_score as _inline_min_place_score,
    _max_rerank_score as _max_rerank_score,
    _min_query_chars_for_images as _min_query_chars_for_images,
    _min_substantive_term_len as _min_substantive_term_len,
    _multi_figure_image_limit as _multi_figure_image_limit,
    default_image_selection_limit as default_image_selection_limit,
)
from iqr_terms import (
    _action_focus_bigrams as _action_focus_bigrams,
    _action_focus_text as _action_focus_text,
    _action_object_cjk as _action_object_cjk,
    _best_query_run_in_line as _best_query_run_in_line,
    _clause_substance_score as _clause_substance_score,
    _figure_matches_query_object as _figure_matches_query_object,
    _image_min_term_overlap as _image_min_term_overlap,
    _is_procedure_steps_query as _is_procedure_steps_query,
    _is_query_subject_echo as _is_query_subject_echo,
    _line_has_query_subject_hit as _line_has_query_subject_hit,
    _line_has_specific_query_overlap as _line_has_specific_query_overlap,
    _line_spans_in_body as _line_spans_in_body,
    _listing_target_head as _listing_target_head,
    _normalize_label_key as _normalize_label_key,
    _normalize_query_for_match as _normalize_query_for_match,
    _procedure_step_spans as _procedure_step_spans,
    _query_clauses as _query_clauses,
    _query_object_terms as _query_object_terms,
    _query_primary_object_term as _query_primary_object_term,
    _query_subject_needles as _query_subject_needles,
    _query_tail_text as _query_tail_text,
    _query_terms as _query_terms,
    _ref_passes_focus_bigram_gate as _ref_passes_focus_bigram_gate,
    _subject_action_clauses as _subject_action_clauses,
    _subject_from_machine_field_line as _subject_from_machine_field_line,
    _subject_object_bigrams as _subject_object_bigrams,
    _suffix_focus_bigrams as _suffix_focus_bigrams,
    _term_overlap_ratio as _term_overlap_ratio,
)
from iqr_store import (
    _cl_path_index as _cl_path_index,
    _collect_figure_refs as _collect_figure_refs,
    _context_for_image_scan as _context_for_image_scan,
    _dedupe_doc_list as _dedupe_doc_list,
    _dedupe_doc_list_by_chunk_identity as _dedupe_doc_list_by_chunk_identity,
    _doc_basename as _doc_basename,
    _doc_chunk_order_index as _doc_chunk_order_index,
    _doc_content as _doc_content,
    _doc_content_key as _doc_content_key,
    _doc_matches_cited_hints as _doc_matches_cited_hints,
    _doc_storage_chunk_id as _doc_storage_chunk_id,
    _eligible_figure_refs as _eligible_figure_refs,
    _first_figure_ref_from_doc as _first_figure_ref_from_doc,
    _is_multi_source_retrieval as _is_multi_source_retrieval,
    _kv_chunk_row as _kv_chunk_row,
    _kv_store_cache as _kv_store_cache,
    _kv_store_mtime as _kv_store_mtime,
    _kv_text_chunks_store as _kv_text_chunks_store,
    _load_content_list_items as _load_content_list_items,
    _load_content_list_items_cached as _load_content_list_items_cached,
    _load_manual_chunks_for_locality as _load_manual_chunks_for_locality,
    _merged_source_hints as _merged_source_hints,
    _pipeline_content_list_entries as _pipeline_content_list_entries,
    _pipeline_parse_roots as _pipeline_parse_roots,
    _ranked_retrieval_lines as _ranked_retrieval_lines,
    _ref_matches_source_hints as _ref_matches_source_hints,
    _refs_from_retrieved_docs_text as _refs_from_retrieved_docs_text,
    _source_hint_matches_doc as _source_hint_matches_doc,
    _source_hints_from_retrieved_docs as _source_hints_from_retrieved_docs,
    _source_hints_from_text as _source_hints_from_text,
    _source_key_from_path as _source_key_from_path,
    _unique_retrieved_doc_count as _unique_retrieved_doc_count,
    merge_context_for_images as merge_context_for_images,
    text_from_retrieved_docs as text_from_retrieved_docs,
)
from iqr_align import (
    _ANSWER_REF_RE as _ANSWER_REF_RE,
    _CITATION_PUNCT_RE as _CITATION_PUNCT_RE,
    _PDF_NAME_RE as _PDF_NAME_RE,
    _REF_LINE_RE as _REF_LINE_RE,
    _SECTION_HEADING_RE as _SECTION_HEADING_RE,
    _SECTION_NUM_RE as _SECTION_NUM_RE,
    _answer_chunk_term_overlap as _answer_chunk_term_overlap,
    _apply_unified_figure_debug as _apply_unified_figure_debug,
    _chunk_citation_score as _chunk_citation_score,
    _chunk_figure_context_aligns_query as _chunk_figure_context_aligns_query,
    _chunk_subject_score as _chunk_subject_score,
    _cross_manual_has_aligned_figures as _cross_manual_has_aligned_figures,
    _figure_ref_passes_align_gate as _figure_ref_passes_align_gate,
    _image_retrieval_focus_min_overlap as _image_retrieval_focus_min_overlap,
    _line_citation_overlap as _line_citation_overlap,
    _normalize_citation_blob as _normalize_citation_blob,
    _query_aligned_figure_candidate_docs as _query_aligned_figure_candidate_docs,
    _ref_aligns_with_query_label as _ref_aligns_with_query_label,
    _ref_aligns_with_retrieval_focus as _ref_aligns_with_retrieval_focus,
    _ref_blob as _ref_blob,
    _ref_effective_label as _ref_effective_label,
    _ref_inline_context_text as _ref_inline_context_text,
    _ref_inline_in_retrieved_context as _ref_inline_in_retrieved_context,
    _ref_label_aligns_with_line as _ref_label_aligns_with_line,
    _ref_passes_image_align_gate as _ref_passes_image_align_gate,
    _ref_structure_align_text as _ref_structure_align_text,
    _summarize_ref as _summarize_ref,
    _text_alignment as _text_alignment,
    _truncate_ref_text as _truncate_ref_text,
    _trust_llm_chunk_images as _trust_llm_chunk_images,
)
from iqr_anchor import (
    _anchor_align_blob as _anchor_align_blob,
    _anchor_chunks_by_query_section as _anchor_chunks_by_query_section,
    _anchor_cite_bonus as _anchor_cite_bonus,
    _anchor_inline_same_chunk as _anchor_inline_same_chunk,
    _anchor_section_carries_subject as _anchor_section_carries_subject,
    _best_anchor_chunk as _best_anchor_chunk,
    _best_figure_ref_for_anchor_align as _best_figure_ref_for_anchor_align,
    _best_inline_figure_from_pool as _best_inline_figure_from_pool,
    _best_section_id_from_content as _best_section_id_from_content,
    _chunk_anchor_structural_adjustment as _chunk_anchor_structural_adjustment,
    _chunk_belongs_to_anchor_sections as _chunk_belongs_to_anchor_sections,
    _chunk_discriminative_heading_bonus as _chunk_discriminative_heading_bonus,
    _chunk_is_short_section_heading as _chunk_is_short_section_heading,
    _chunk_locality_image_enabled as _chunk_locality_image_enabled,
    _chunk_locality_window as _chunk_locality_window,
    _chunk_query_section_score as _chunk_query_section_score,
    _chunk_section_title_line as _chunk_section_title_line,
    _expand_pool_with_same_section_neighbors as _expand_pool_with_same_section_neighbors,
    _figure_doc_for_anchor_neighbor as _figure_doc_for_anchor_neighbor,
    _figure_ref_from_content_list_for_target as _figure_ref_from_content_list_for_target,
    _find_anchor_in_answer as _find_anchor_in_answer,
    _find_semantic_anchor_in_answer as _find_semantic_anchor_in_answer,
    _image_anchor_max_sections as _image_anchor_max_sections,
    _image_anchor_min_line_overlap as _image_anchor_min_line_overlap,
    _image_anchor_mode as _image_anchor_mode,
    _is_section_number_heading as _is_section_number_heading,
    _llm_chunk_locality_max_add as _llm_chunk_locality_max_add,
    _llm_chunk_locality_skipped as _llm_chunk_locality_skipped,
    _llm_chunk_locality_window as _llm_chunk_locality_window,
    _load_figure_chunks_for_manual_paths as _load_figure_chunks_for_manual_paths,
    _order_neighbor_candidates_for_anchor as _order_neighbor_candidates_for_anchor,
    _pick_anchor_sections as _pick_anchor_sections,
    _pool_has_query_aligned_figure_chunks as _pool_has_query_aligned_figure_chunks,
    _primary_section_id as _primary_section_id,
    _query_section_anchor_min_score as _query_section_anchor_min_score,
    _ref_anchored_in_retrieved_text as _ref_anchored_in_retrieved_text,
    _ref_conflicts_anchor_sections as _ref_conflicts_anchor_sections,
    _ref_context_subject_aligns as _ref_context_subject_aligns,
    _ref_section_subject as _ref_section_subject,
    _section_heading_before_line as _section_heading_before_line,
    _section_id_from_line_or_context as _section_id_from_line_or_context,
    _section_ids_in_text as _section_ids_in_text,
    _section_line_query_boost as _section_line_query_boost,
    _section_title_from_heading_line as _section_title_from_heading_line,
    _sections_compatible as _sections_compatible,
    _should_expand_cited_manual_kv_pool as _should_expand_cited_manual_kv_pool,
    _strip_section_prefix as _strip_section_prefix,
    _supplement_answer_topic_figure_chunks as _supplement_answer_topic_figure_chunks,
    _supplement_component_listing_figure_chunks as _supplement_component_listing_figure_chunks,
    _supplement_cross_manual_figure_chunks as _supplement_cross_manual_figure_chunks,
    _valid_manual_section_id as _valid_manual_section_id,
    llm_chunk_locality_enabled as llm_chunk_locality_enabled,
    merge_order_neighbors_into_llm_chunks as merge_order_neighbors_into_llm_chunks,
    query_section_anchor_enabled as query_section_anchor_enabled,
    supplement_unique_chunks_with_order_neighbors as supplement_unique_chunks_with_order_neighbors,
)
from iqr_figure_target import (
    _ANSWER_STRUCTURAL_LABEL_KEYS as _ANSWER_STRUCTURAL_LABEL_KEYS,
    _BULLET_ALIAS_SUFFIX as _BULLET_ALIAS_SUFFIX,
    _CATALOG_MODEL_MARKER as _CATALOG_MODEL_MARKER,
    _COMPONENT_BULLET_RE as _COMPONENT_BULLET_RE,
    _COMPONENT_FIELD_KEYS as _COMPONENT_FIELD_KEYS,
    _GENERIC_CYCLE_LABEL_RE as _GENERIC_CYCLE_LABEL_RE,
    _MACHINE_FIELD_LINE_RE as _MACHINE_FIELD_LINE_RE,
    _MACHINE_LINE_COMPONENT_PATTERNS as _MACHINE_LINE_COMPONENT_PATTERNS,
    _MAINT_CYCLE_VALUE_RE as _MAINT_CYCLE_VALUE_RE,
    _MAINT_TOPIC_RE as _MAINT_TOPIC_RE,
    _anchor_maintenance_spans as _anchor_maintenance_spans,
    _answer_body_for_citation_match as _answer_body_for_citation_match,
    _answer_bullet_component_head as _answer_bullet_component_head,
    _answer_bullet_lines_for_figure_targets as _answer_bullet_lines_for_figure_targets,
    _answer_bullets_for_inline_figure_match as _answer_bullets_for_inline_figure_match,
    _answer_has_multi_section_markdown as _answer_has_multi_section_markdown,
    _answer_image_span_targets as _answer_image_span_targets,
    _answer_listing_spans as _answer_listing_spans,
    _answer_logic_lines as _answer_logic_lines,
    _answer_paragraph_blocks as _answer_paragraph_blocks,
    _answer_primary_listing_body as _answer_primary_listing_body,
    _answer_section_topics as _answer_section_topics,
    _answer_text_for_listing as _answer_text_for_listing,
    _answer_text_for_placement as _answer_text_for_placement,
    _answer_topic_min_overlap as _answer_topic_min_overlap,
    _answer_weak_consistency_gate as _answer_weak_consistency_gate,
    _best_anchor_doc_for_machine as _best_anchor_doc_for_machine,
    _best_figure_doc_for_component as _best_figure_doc_for_component,
    _best_figure_ref_for_listing_target as _best_figure_ref_for_listing_target,
    _build_machine_bullet_manual_placements as _build_machine_bullet_manual_placements,
    _bullet_head_in_inline_context as _bullet_head_in_inline_context,
    _chunk_aligns_answer_bullet_via_inline_figure as _chunk_aligns_answer_bullet_via_inline_figure,
    _chunk_heading_blob as _chunk_heading_blob,
    _chunk_is_table_heavy as _chunk_is_table_heavy,
    _chunk_is_title_only as _chunk_is_title_only,
    _chunk_is_toc_heavy as _chunk_is_toc_heavy,
    _chunk_matches_answer_topic as _chunk_matches_answer_topic,
    _cite_pool_chunk_ids as _cite_pool_chunk_ids,
    _cited_manual_hints_from_answer as _cited_manual_hints_from_answer,
    _cited_manual_pdf_stems as _cited_manual_pdf_stems,
    _component_listing_span_targets as _component_listing_span_targets,
    _component_spans_from_answer as _component_spans_from_answer,
    _components_from_machine_line_value as _components_from_machine_line_value,
    _cross_listing_figure_topics as _cross_listing_figure_topics,
    _doc_matches_manual_hint as _doc_matches_manual_hint,
    _enrich_ref_from_image_block as _enrich_ref_from_image_block,
    _figure_context_from_answer_docs as _figure_context_from_answer_docs,
    _figure_for_target as _figure_for_target,
    _figure_label_matches_query as _figure_label_matches_query,
    _figure_ref_matches_listing_target as _figure_ref_matches_listing_target,
    _figure_ref_matches_target_topic as _figure_ref_matches_target_topic,
    _figure_target_topic_text as _figure_target_topic_text,
    _filter_cross_listing_pair_targets as _filter_cross_listing_pair_targets,
    _finalize_figure_target_row as _finalize_figure_target_row,
    _heading_before_image_block as _heading_before_image_block,
    _infer_listing_machine_context as _infer_listing_machine_context,
    _infer_listing_pairs_from_cited_chunks as _infer_listing_pairs_from_cited_chunks,
    _is_answer_footnote_line as _is_answer_footnote_line,
    _is_answer_structural_label as _is_answer_structural_label,
    _is_catalog_or_model_listing_query as _is_catalog_or_model_listing_query,
    _is_component_field_name as _is_component_field_name,
    _is_component_listing_across_machines as _is_component_listing_across_machines,
    _is_cover_page_ref as _is_cover_page_ref,
    _is_generic_cycle_only_label as _is_generic_cycle_only_label,
    _is_listing_scope_query as _is_listing_scope_query,
    _is_maintenance_cycle_query as _is_maintenance_cycle_query,
    _is_maintenance_cycle_value as _is_maintenance_cycle_value,
    _is_multi_machine_comparison_query as _is_multi_machine_comparison_query,
    _is_ordinal_enumeration_bullet_head as _is_ordinal_enumeration_bullet_head,
    _is_toc_or_directory_line as _is_toc_or_directory_line,
    _is_usable_source_figure_label as _is_usable_source_figure_label,
    _label_matches_listing_target as _label_matches_listing_target,
    _listing_component_from_maint_chunk as _listing_component_from_maint_chunk,
    _listing_mode_active as _listing_mode_active,
    _listing_target_phrases as _listing_target_phrases,
    _listing_targets_anchored_in_text as _listing_targets_anchored_in_text,
    _listing_targets_with_query_line_overlap as _listing_targets_with_query_line_overlap,
    _listing_topics_from_pool as _listing_topics_from_pool,
    _machine_bullet_lines_from_answer as _machine_bullet_lines_from_answer,
    _machine_bullet_subject as _machine_bullet_subject,
    _machine_bullet_subject_variants as _machine_bullet_subject_variants,
    _machine_component_listing_pair_targets as _machine_component_listing_pair_targets,
    _machine_component_targets_from_answer as _machine_component_targets_from_answer,
    _machine_from_section_title as _machine_from_section_title,
    _machine_spans_from_answer as _machine_spans_from_answer,
    _machine_targets_from_answer as _machine_targets_from_answer,
    _maintenance_content_label_for_ref as _maintenance_content_label_for_ref,
    _maintenance_content_spans as _maintenance_content_spans,
    _maintenance_topics_in_text as _maintenance_topics_in_text,
    _manual_hint_for_component as _manual_hint_for_component,
    _manual_scoped_cite_pool as _manual_scoped_cite_pool,
    _order_listing_targets_by_hints as _order_listing_targets_by_hints,
    _pair_component_ref_align as _pair_component_ref_align,
    _pair_component_spans_from_answer as _pair_component_spans_from_answer,
    _pick_figure_ref_for_target_kind as _pick_figure_ref_for_target_kind,
    _preserve_source_figure_labels as _preserve_source_figure_labels,
    _ref_aligns_answer_bullets_via_inline_context as _ref_aligns_answer_bullets_via_inline_context,
    _ref_aligns_for_multi_figure_listing as _ref_aligns_for_multi_figure_listing,
    _ref_maint_section_id as _ref_maint_section_id,
    _ref_maintenance_topic as _ref_maintenance_topic,
    _ref_matches_figure_focus as _ref_matches_figure_focus,
    _ref_matches_machine_bullet_theme as _ref_matches_machine_bullet_theme,
    _ref_matches_manual_hint as _ref_matches_manual_hint,
    _ref_matches_query_theme_in_evidence as _ref_matches_query_theme_in_evidence,
    _refs_from_unified_figure_targets as _refs_from_unified_figure_targets,
    _relabel_dc_chunks as _relabel_dc_chunks,
    _resolve_doc_with_order_index as _resolve_doc_with_order_index,
    _resolve_known_machine_name as _resolve_known_machine_name,
    _resolve_manual_hint_for_figure_targets as _resolve_manual_hint_for_figure_targets,
    _retrieval_prefers_catalog_field as _retrieval_prefers_catalog_field,
    _should_use_unified_figure_targets as _should_use_unified_figure_targets,
    _single_figure_supplement_topics as _single_figure_supplement_topics,
    _source_figure_label as _source_figure_label,
    _span_keep_listing_targets as _span_keep_listing_targets,
    _strict_object_image_gate as _strict_object_image_gate,
    _subjects_from_machine_field_value as _subjects_from_machine_field_value,
    _topic_has_figure_support_in_pool as _topic_has_figure_support_in_pool,
    _topic_in_inline_figure_context as _topic_in_inline_figure_context,
    _topic_overlaps_query as _topic_overlaps_query,
    _topic_supported_by_kept_chunks as _topic_supported_by_kept_chunks,
    detect_table_filter_signal as detect_table_filter_signal,
    extract_figure_targets as extract_figure_targets,
    filter_docs_cited_by_answer as filter_docs_cited_by_answer,
)
from iqr_explain import (
    explain_query_images as explain_query_images,
    explain_retrieval_supports_images as explain_retrieval_supports_images,
    query_wants_kb_images as query_wants_kb_images,
    retrieval_supports_images as retrieval_supports_images,
)
from iqr_placement import (
    _api_images_from_figure_refs as _api_images_from_figure_refs,
    _apply_placement_reindex as _apply_placement_reindex,
    _build_caption_fallback_placements as _build_caption_fallback_placements,
    _build_semantic_inline_placements as _build_semantic_inline_placements,
    _cycle_caption_block_placement as _cycle_caption_block_placement,
    _fallback_end_placements as _fallback_end_placements,
    build_inline_placements as build_inline_placements,
    images_for_api as images_for_api,
    resolve_query_images as resolve_query_images,
)

__all__ = [
    "build_image_ref_block",
    "flatten_image_refs_for_skip_multimodal",
    "extract_image_refs_from_context",
    "build_inline_placements",
    "images_for_api",
    "resolve_query_images",
    "default_image_selection_limit",
    "query_wants_kb_images",
    "retrieval_supports_images",
    "encode_media_token",
    "decode_media_token",
    "is_safe_media_path",
    "normalize_context_for_image_parse",
]
